spring:
  datasource:
    dynamic:
      primary: master
      datasource:
        master:
          url: jdbc:mysql://127.0.0.1:3306/bonelf-support?characterEncoding=UTF-8&useUnicode=true&useSSL=false&tinyInt1isBit=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai
          username: root
          password: 567215
          driver-class-name: com.mysql.jdbc.Driver
      # 多数据源配置
      #multi-datasource1:
  redis:
    database: 0
    host: localhost
    port: 6379

ws:
  port: 8802
  context-path: /
#  ssl:
#    path: notnull