bonelf:
  base-url: localhost
  app-name: bonelf总结项目
  oauth2:
    jwt:
      # customer:
      signing-key: 123456
      # classpath:
      keystore: /tls/example.p12
      password: =bonelf=
      alias: bonelf
    no-auth:
      - /noAuth/**
      - /verificationCode/**
  mail:
    password: ccy297115649
    smtp: smtp.ym.163.com
    username: me@chenchengyuan.com